### ISSUE TITLE
Error: 0x80070057

### ISSUE THREAD

**Issue by Zoweb** [cpdt/slinky#11] opened 2016-09-20 02:46 UTC
When installing Slinky, after using the default values on all options, I get the following error:

```
Excellent! Beginning installation from https://raw.githubusercontent.com/cpdt/slinky/develop
  Ensuring curl is installed
Error: 0x80070057
Failed to run sudo apt-get install curl -y, continuing anyway
Error: 0x80070057
Failed to run sudo mkdir -p "/usr/local/bin" - Slinky is NOT installed.
Installation cannot continue, and has been aborted.
```

**Comment by cpdt** [comment] 2016-09-20 02:58
Unfortunately, this seems to be an issue with Ubuntu for Windows, discussed in https://github.com/Microsoft/BashOnWindows/issues/461 which would require a rewrite of the way the Slinky installer executes Bash commands.

I think I have a potential way to work around this, it's a bit ugly and may not work but I'll fiddle around and see.

**Comment by cpdt** [comment] 2016-09-20 03:40
Just pushed a fix for this, but haven't had the chance to verify that it works on Bash for Windows (confirmed it working on Git Bash).

**Closed as completed** 2017-04-12 06:31 UTC
